name: release

on:
  push:
    tags: 
      - '[1-9]+.[0-9]+.[0-9]+'
      - '[1-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  draft-release:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          draft: true
          prerelease: ${{ env.PRERELEASE }}
          files: |
            LICENSE
          env:
            PRERELEASE: ${{ contains(github.ref, '-rc.') }}

